import { readFileSync, writeFileSync } from 'fs'

const NAME_ZH = {
  // academic
  'Anthropologist': '人类学家',
  'Geographer': '地理学家',
  'Historian': '历史学家',
  'Narratologist': '叙事学家',
  'Psychologist': '心理学家',
  // design
  'Brand Guardian': '品牌守护者',
  'Image Prompt Engineer': '图像提示工程师',
  'Inclusive Visuals Specialist': '无障碍视觉专家',
  'UI Designer': 'UI 设计师',
  'UX Architect': '用户体验架构师',
  'UX Researcher': '用户研究员',
  'Visual Storyteller': '视觉叙事师',
  'Whimsy Injector': '创意注入师',
  // engineering
  'AI Data Remediation Engineer': 'AI 数据修复工程师',
  'AI Engineer': 'AI 工程师',
  'Autonomous Optimization Architect': '自主优化架构师',
  'Backend Architect': '后端架构师',
  'Code Reviewer': '代码审查员',
  'Data Engineer': '数据工程师',
  'Database Optimizer': '数据库优化师',
  'DevOps Automator': 'DevOps 自动化工程师',
  'Embedded Firmware Engineer': '嵌入式固件工程师',
  'Feishu Integration Developer': '飞书集成开发工程师',
  'Frontend Developer': '前端开发工程师',
  'Git Workflow Master': 'Git 工作流专家',
  'Incident Response Commander': '事故响应指挥官',
  'Mobile App Builder': '移动应用开发工程师',
  'Rapid Prototyper': '快速原型工程师',
  'Security Engineer': '安全工程师',
  'Senior Developer': '高级开发工程师',
  'Software Architect': '软件架构师',
  'Solidity Smart Contract Engineer': 'Solidity 智能合约工程师',
  'SRE (Site Reliability Engineer)': '网站可靠性工程师',
  'Technical Writer': '技术文档工程师',
  'Threat Detection Engineer': '威胁检测工程师',
  'WeChat Mini Program Developer': '微信小程序开发工程师',
  // game-development
  'Blender Add-on Engineer': 'Blender 插件工程师',
  'Game Audio Engineer': '游戏音频工程师',
  'Game Designer': '游戏设计师',
  'Godot Gameplay Scripter': 'Godot 游戏脚本工程师',
  'Godot Multiplayer Engineer': 'Godot 多人游戏工程师',
  'Godot Shader Developer': 'Godot 着色器开发工程师',
  'Level Designer': '关卡设计师',
  'Narrative Designer': '叙事设计师',
  'Roblox Avatar Creator': 'Roblox 虚拟形象创作者',
  'Roblox Experience Designer': 'Roblox 体验设计师',
  'Roblox Systems Scripter': 'Roblox 系统脚本工程师',
  'Technical Artist': '技术美术',
  'Unity Architect': 'Unity 架构师',
  'Unity Editor Tool Developer': 'Unity 编辑器工具开发工程师',
  'Unity Multiplayer Engineer': 'Unity 多人游戏工程师',
  'Unity Shader Graph Artist': 'Unity 着色器图艺术师',
  'Unreal Multiplayer Architect': '虚幻引擎多人游戏架构师',
  'Unreal Systems Engineer': '虚幻引擎系统工程师',
  'Unreal Technical Artist': '虚幻引擎技术美术',
  'Unreal World Builder': '虚幻引擎世界构建师',
  // marketing
  'AI Citation Strategist': 'AI 引用策略师',
  'App Store Optimizer': '应用商店优化专家',
  'Baidu SEO Specialist': '百度 SEO 专家',
  'Bilibili Content Strategist': 'B 站内容策略师',
  'Book Co-Author': '图书联合作者',
  'Carousel Growth Engine': '轮播图增长引擎',
  'China E-Commerce Operator': '中国电商运营师',
  'Content Creator': '内容创作者',
  'Cross-Border E-Commerce Specialist': '跨境电商专家',
  'Douyin Strategist': '抖音策略师',
  'Growth Hacker': '增长黑客',
  'Instagram Curator': 'Instagram 内容策展人',
  'Kuaishou Strategist': '快手策略师',
  'LinkedIn Content Creator': 'LinkedIn 内容创作者',
  'Livestream Commerce Coach': '直播电商教练',
  'Podcast Strategist': '播客策略师',
  'Private Domain Operator': '私域运营专家',
  'Reddit Community Builder': 'Reddit 社区运营',
  'SEO Specialist': 'SEO 专家',
  'Short-Video Editing Coach': '短视频剪辑教练',
  'Social Media Strategist': '社交媒体策略师',
  'TikTok Strategist': 'TikTok 策略师',
  'Twitter Engager': 'Twitter 互动运营',
  'WeChat Official Account Manager': '微信公众号运营',
  'Weibo Strategist': '微博策略师',
  'Xiaohongshu Specialist': '小红书专家',
  'Zhihu Strategist': '知乎策略师',
  'Paid Media Auditor': '付费媒体审计师',
  'Ad Creative Strategist': '广告创意策略师',
  'Paid Social Strategist': '付费社交策略师',
  'PPC Campaign Strategist': 'PPC 竞价投放策略师',
  'Programmatic & Display Buyer': '程序化展示广告采购师',
  'Search Query Analyst': '搜索词分析师',
  'Tracking & Measurement Specialist': '追踪与数据分析专家',
  // product
  'Behavioral Nudge Engine': '行为助推引擎',
  'Feedback Synthesizer': '反馈综合分析师',
  'Product Manager': '产品经理',
  'Sprint Prioritizer': '迭代优先级规划师',
  'Trend Researcher': '趋势研究员',
  'Experiment Tracker': '实验追踪师',
  // project-management
  'Jira Workflow Steward': 'Jira 工作流管理员',
  'Project Shepherd': '项目牧羊人',
  'Studio Operations': '工作室运营',
  'Studio Producer': '工作室制片人',
  'Senior Project Manager': '高级项目经理',
  // sales
  'Account Strategist': '客户策略师',
  'Sales Coach': '销售教练',
  'Deal Strategist': '交易策略师',
  'Discovery Coach': '需求挖掘教练',
  'Sales Engineer': '销售工程师',
  'Outbound Strategist': '外呼销售策略师',
  'Pipeline Analyst': '销售漏斗分析师',
  'Proposal Strategist': '提案策略师',
  // spatial-computing
  'macOS Spatial/Metal Engineer': 'macOS 空间/Metal 工程师',
  'Terminal Integration Specialist': '终端集成专家',
  'visionOS Spatial Engineer': 'visionOS 空间工程师',
  'XR Cockpit Interaction Specialist': 'XR 座舱交互专家',
  'XR Immersive Developer': 'XR 沉浸式开发工程师',
  'XR Interface Architect': 'XR 界面架构师',
  // specialized
  'Accounts Payable Agent': '应付账款代理',
  'Agentic Identity & Trust Architect': 'Agent 身份与信任架构师',
  'Agents Orchestrator': 'Agent 编排师',
  'Automation Governance Architect': '自动化治理架构师',
  'Blockchain Security Auditor': '区块链安全审计师',
  'Compliance Auditor': '合规审计师',
  'Corporate Training Designer': '企业培训设计师',
  'Data Consolidation Agent': '数据整合代理',
  'Government Digital Presales Consultant': '政府数字化售前顾问',
  'Healthcare Marketing Compliance Specialist': '医疗营销合规专家',
  'Identity Graph Operator': '身份图谱运营师',
  'LSP/Index Engineer': 'LSP/索引工程师',
  'Recruitment Specialist': '招聘专家',
  'Report Distribution Agent': '报告分发代理',
  'Sales Data Extraction Agent': '销售数据提取代理',
  'Cultural Intelligence Strategist': '文化智商策略师',
  'Developer Advocate': '开发者关系布道师',
  'Document Generator': '文档生成器',
  'French Consulting Market Navigator': '法国咨询市场导航师',
  'Korean Business Navigator': '韩国商业导航师',
  'MCP Builder': 'MCP 构建者',
  'Model QA Specialist': '模型质量保证专家',
  'Salesforce Architect': 'Salesforce 架构师',
  'Workflow Architect': '工作流架构师',
  'Study Abroad Advisor': '留学顾问',
  'Supply Chain Strategist': '供应链策略师',
  'ZK Steward': 'ZK 守护者',
  // support
  'Analytics Reporter': '分析报告员',
  'Executive Summary Generator': '执行摘要生成器',
  'Finance Tracker': '财务追踪师',
  'Infrastructure Maintainer': '基础设施维护工程师',
  'Legal Compliance Checker': '法律合规检查员',
  'Support Responder': '客服响应专员',
  // testing
  'Accessibility Auditor': '无障碍审计师',
  'API Tester': 'API 测试工程师',
  'Evidence Collector': '证据收集员',
  'Performance Benchmarker': '性能基准测试师',
  'Reality Checker': '现实核查员',
  'Test Results Analyzer': '测试结果分析师',
  'Tool Evaluator': '工具评估师',
  'Workflow Optimizer': '工作流优化师',
}

let content = readFileSync('src/data/agents.ts', 'utf8')

// Update Agent interface to add nameZh
content = content.replace(
  'export interface Agent {\n  id: string\n  name: string\n  emoji: string',
  'export interface Agent {\n  id: string\n  name: string\n  nameZh: string\n  emoji: string'
)

// For each agent entry, inject nameZh after name
content = content.replace(/"name": "([^"]+)"/g, (match, name) => {
  const nameZh = NAME_ZH[name]
  if (!nameZh) {
    console.warn(`Missing translation: ${name}`)
    return match + `,\n    "nameZh": "${name}"`
  }
  return match + `,\n    "nameZh": "${nameZh}"`
})

writeFileSync('src/data/agents.ts', content)
console.log('Done')
